# Generated by Django 4.1.6 on 2023-02-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='file',
            new_name='menu',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voted_at',
        ),
    ]
